Grid component page
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #10
Opened 2022-10-03 12:33 UTC by PASHANSX

2022-10-03 12:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-05 08:06 UTC, GSemikozov requested changes

2022-10-05 08:06 UTC, GSemikozov commented on components/container/container.css
> +.container_grid {
это все-таки не контейнер, а блок, формирующий разметку целой секции, поэтому - лучше оформить как отдельный блок

2022-10-05 08:06 UTC, GSemikozov commented on components/container/container.css
> +    grid-template: 1fr / calc(229px + 56px) minmax(400px, 825px);
считать эти 56px не стоит, лучше использовать gap сразу. И дальше - minmax(400px, 825px) это лишнее и сложно, гораздо проще будет задать 1fr

2022-10-05 08:06 UTC, GSemikozov commented on components/footer/footer.css
> +.footer-title_grid {
.footer__title_grid?

2022-10-06 06:10 UTC, GSemikozov requested changes

2022-10-06 06:10 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title-grid {
.footer__title_grid

2022-10-08 06:22 UTC, PASHANSX commented
1

2022-10-08 06:24 UTC, PASHANSX commented
closed

2022-10-09 00:43 UTC, closed without merging