05 lection3/02 modal
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #14
Opened 2022-10-05 11:45 UTC by PASHANSX

2022-10-05 11:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-06 06:11 UTC, GSemikozov requested changes

2022-10-06 06:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
лишний элемент, можно фон сразу задать на уровне блока

2022-10-06 07:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-09 01:00 UTC, closed without merging