06 lection4/04 05 mobile and logo
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #21
Opened 2022-10-18 10:31 UTC by PASHANSX

Вставил логотип, меню справа от логотипа. Написал медиазапросы. Касается файлов index.html и template.html

2022-10-18 10:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-18 19:41 UTC, GSemikozov requested changes

2022-10-18 19:41 UTC, GSemikozov commented on components/header/header.css
> +.header__right-block-item:first-child {
советовал бы это оформить как отдельный блок с меню (нужно подумать над подходящим именем)

2022-10-18 19:41 UTC, GSemikozov commented on components/header/header.css
> +        font-family: 'Inter';
шрифт точно меняется?

2022-10-18 19:41 UTC, GSemikozov commented on components/preview/preview.css
>  .preview__cards-item {
пора вынести карточку как отдельный блок. + паддинги точно совпадают с макетом?

2022-10-18 19:41 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__cards-item-component-block {
и тогда не придется придумывать такие длинные классы

2022-10-19 09:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-23 17:34 UTC, GSemikozov approved these changes

2022-10-23 17:34 UTC, merged