text input
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #27
Opened 2022-10-27 18:07 UTC by PASHANSX

2022-10-27 18:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-28 20:21 UTC, GSemikozov requested changes

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="input-text input-text_success">
в данном случае все заворачивать в лейбл не надо

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="input-text__label">label</div>
вот это как раз и есть семантический лейбл

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 100%;
тогда вот это не надо

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-text_success .input-text__icon-success, .input-text_invalid .input-text__icon-invalid {
.input-text__icon_success, .input-text__icon_invalid

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <input class="input-text__control" type="text" placeholder="Placeholder">
иконки и инпут надо завернуть в общий враппер и позиционировать иконки относительно него

2022-10-28 20:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top: 18px;
см коммент выше - лейбл можем быть опциональным, и если текста над инпутом не будет, то иконка уедет вниз

2022-11-01 10:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-01 10:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-01 13:24 UTC, PASHANSX commented on 07-lection5/04-input/index.html
> +        <label class="input-text input-text_success">
Почему не стоит? Если я не оберну в label, то не будет возможности по клику на label фокусироваться на input-e. Либо без обертки мог бы использовать for в  label и id в input. Но какая разница?

2022-11-01 13:24 UTC, PASHANSX commented on 07-lection5/04-input/index.html
> +            <div class="input-text__label">label</div>
Согласен!

2022-11-01 13:25 UTC, PASHANSX commented on 07-lection5/04-input/input.css
> +    width: 100%;
Если я не укажу width: 100%, то как в таком случае можно растянуть уго на всю ширину? Например, если этот компонент, я хотел бы переиспользовать и он должен будет занимать всю ширину родителя.

2022-11-01 13:25 UTC, PASHANSX commented on 07-lection5/04-input/input.css
> +.input-text_success .input-text__icon-success, .input-text_invalid .input-text__icon-invalid {
Если так указать, то иконки будут наложены друг на друга. Моя идея была в том, что можно управлять отображением иконок манипулированием классами на родительском элементе. Что ты имел в виду?

2022-11-01 13:25 UTC, PASHANSX commented on 07-lection5/04-input/index.html
> +                <input class="input-text__control" type="text" placeholder="Placeholder">
input-text__state - является общим враппером с position: relative. Что нужно сделать дополнительно?

2022-11-01 13:25 UTC, PASHANSX commented on 07-lection5/04-input/input.css
> +    top: 18px;
Позиционирование ведь относительно .input-text__state, а не .input-text.

2022-11-01 13:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-03 21:10 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="input-text input-text_success">
почему не будет? label останется на своей законном месте, над инпутом, просто заворачивать все остальные элементы в лейбл не надо. Почему? Потому, что обычно вместо иконки часто добавляют кнопку, или в хелпер-тексте добавляют ссылки - все это будет работать не так как ожидает пользователь - вместо (или вместе с) кликом по кнопке мы будет уходить в фокус инпута, и это будет нежелательный сайд-эффект.

2022-11-03 21:11 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 100%;
по умолчанию это div = блочный элемент = растягивается на 100% по умолчанию.
в целом - если надо растянуть встраиваемый блок на всю доступную ширину родителя - это делается через родителя, а именно - через класс-микс

2022-11-03 21:12 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-text_success .input-text__icon-success, .input-text_invalid .input-text__icon-invalid {
по умолчанию .input-text__icon { display: none }, а когда надо показать success / error - меняем display на block

2022-11-03 21:13 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <input class="input-text__control" type="text" placeholder="Placeholder">
корректно

2022-11-03 21:13 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top: 18px;
корректно, только тогда так (чтобы не зависеть от высоты иконки): `top: 50%, transform: translateY(-50%)`

2022-11-14 08:54 UTC, PASHANSX commented on 07-lection5/04-input/index.html
> +        <label class="input-text input-text_success">
Понял. Спасибо!

2022-11-14 21:48 UTC, GSemikozov requested changes

2022-11-14 21:48 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input-text__icon input-text__icon-success">
модификатор input-text__icon_success

2022-11-14 21:48 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input-text__icon input-text__icon-invalid">
input-text__icon_invalid

2022-11-17 11:07 UTC, GSemikozov approved these changes

2022-11-17 11:07 UTC, merged