07-lection5/05-tabs-main-page
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #28
Opened 2022-11-01 14:58 UTC by PASHANSX

2022-11-01 14:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-03 21:16 UTC, GSemikozov requested changes

2022-11-03 21:16 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs > input[name="tabs"] {
во всем файле нужно заменить селекторы тегов на классы по БЭМ + где возможно избежать ненужного использования вложенных селекторов

2022-11-03 21:16 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs > input[name="tabs"] {
и не вижу механизма переключения секций tabs__content

2022-11-14 08:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-14 08:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-14 09:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-14 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-14 20:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-14 21:49 UTC, GSemikozov requested changes

2022-11-14 21:49 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs label {
.tabs__label

2022-11-15 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-15 16:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-17 11:08 UTC, GSemikozov approved these changes

2022-11-17 11:08 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-11-17 11:09 UTC, GSemikozov approved these changes

2022-11-17 11:09 UTC, merged