buttons finished
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #4
Opened 2022-09-25 07:07 UTC by PASHANSX

2022-09-25 07:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-26 08:21 UTC, GSemikozov requested changes

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    --bg-button-primary-default: var(--primary);
переменные я бы советовал пока убрать - добавить после того, как об этом расскажу на лекции.
если коротко - создавать локальные переменные для значений которые не повторяются, это перебор.

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает свойств высоты и паддингов

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
их мы можем указать именно на этом уровне, у нас в макете нет кнопок разных размеров

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_size_m {
см коммент выше

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лучше pointer-events: none

2022-09-26 08:21 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                    <span class="button__label">
кнопки у нас максимально простые, лишняя прослойка в виде span элемента нам не потребуется, можно удалить

2022-09-26 18:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 16:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 16:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 16:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 18:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 20:52 UTC, GSemikozov approved these changes

2022-09-27 20:52 UTC, merged