03 lection1/02 accordion
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #6
Opened 2022-09-28 14:18 UTC by PASHANSX

2022-09-28 14:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 21:02 UTC, GSemikozov requested changes

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину не стоит жестко фиксировать, лишнее

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    background: #FFFFFF;
уже можно применять переменные

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .icon-arrow {
семантически класс .icon-arrow  означает что это отдельный блок. Но - на самом деле это составная часть аккордиона, так что - .accordion__icon-arrow

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    transform: translateY(-50%) rotate(0deg);
двигать через translateY не надо, тут только поворачиваем иконку

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    position: absolute;
лишняя обертка вокруг иконки + позиционирование мы еще не изучали, так что можно удалить и абсолют не использовать. Вместо этого можно более простым способом отправить иконку к правому краю (флекс)

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__icon-container_valign_center {
удалим

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 18px 8px 0;
точно ли здесь должны быть такие марджины? лучше свериться с макетом

2022-09-28 21:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .icon-arrow {
и при открытом .accordion__item[open] паддинг снизу будет другой

2022-09-29 07:51 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 18px 8px 0;
Проверяю еще раз. Padding основного контейнера `.accordion__item` вне зависимости открыт аккордеон или закрыт: сверху и снизу 24px, слева и справа 32px.
Когда контейнер открывается, появляется блок текста аккордеона `.accordion__description`, где расстояние от нижней границы блока текста до `border-a` аккордеона равно теперь уже 32px, вместо 24px ранее, когда он был скрыт.
Раз это так, к блоку текста снизу я добавлю `8px`, таким образом с учетом `padding` снизу основного контейнера, получается: 8px + 24px = 32px;
Margin блока текста `.accordion__description` также имеет внешний отступ сверху от блока заголовка `.accordion__summary` - 16px и отступ справа, который равен ширине иконки стрелки - 18px. Слева отступов нет.
Вроде бы все верно. Или я не правильно читаю макет?

2022-09-29 07:52 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +.accordion__icon-container_valign_center {
+

2022-09-29 07:52 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +    position: absolute;
+

2022-09-29 07:52 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +    transform: translateY(-50%) rotate(0deg);
+

2022-09-29 07:54 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .icon-arrow {
+

2022-09-29 07:55 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +    background: #FFFFFF;
+

2022-09-29 07:55 UTC, PASHANSX commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
+

2022-09-29 08:55 UTC, GSemikozov requested changes

2022-09-29 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item">
элементы блока не могут существовать вне своего блока, так что их надо завернуть в общий div с классом accordion

2022-09-29 08:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 18px 0 0;
это внутренние отступы

2022-09-29 20:03 UTC, GSemikozov approved these changes

2022-09-29 20:03 UTC, merged