skeleton
js-tasks-ru/htmlcss-20220919_flyerok86 pull request #9
Opened 2022-09-28 19:00 UTC by PASHANSX

2022-09-28 19:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 08:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 08:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 09:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 17:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 17:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 18:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 18:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 18:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 18:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-30 06:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 14:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 14:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 16:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 16:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 16:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-02 19:52 UTC, GSemikozov requested changes

2022-10-02 19:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 64px;
не нужно фиксировать высоту (например если захотим добавить еще 1 линию)

2022-10-02 19:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header .skeleton__gradient-block:first-of-type {
лучше все-таки более универсальные модификаторы, чем привязка с другим элементам блока

2022-10-02 19:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header .skeleton__gradient-block:last-of-type {
и тут

2022-10-02 19:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 48px;
высоту удалим

2022-10-03 08:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 08:04 UTC, GSemikozov approved these changes

2022-10-03 08:04 UTC, merged